CREATE TYPE subject_kind AS ENUM ('group', 'leaf');

ALTER TYPE transaction_type RENAME TO transaction_type_old;

CREATE TYPE transaction_type AS ENUM (
  'purchase',
  'reservation',
  'reservation_release',
  'session_debit',
  'refund',
  'adjustment',
  'cancellation_fee'
);

ALTER TABLE credit_transactions
  ALTER COLUMN type TYPE transaction_type
  USING (
    CASE
      WHEN type::text = 'Purchase' THEN 'purchase'
      WHEN type::text = 'Session Debit' AND session_id IS NOT NULL THEN 'reservation'
      WHEN type::text = 'Session Debit' THEN 'session_debit'
      WHEN type::text = 'Refund' THEN 'refund'
      WHEN type::text = 'Adjustment' THEN 'adjustment'
      WHEN type::text = 'Cancellation Fee' THEN 'cancellation_fee'
      ELSE lower(replace(type::text, ' ', '_'))
    END
  )::transaction_type;

DROP TYPE transaction_type_old;

ALTER TABLE subjects RENAME TO subjects_legacy;

CREATE TABLE subjects (
  id integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME subjects_new_id_seq) PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL,
  kind subject_kind NOT NULL,
  parent_subject_id integer,
  parent_subject_kind subject_kind,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subjects_slug_unique UNIQUE (slug),
  CONSTRAINT subjects_id_kind_unique UNIQUE (id, kind),
  CONSTRAINT subjects_parent_name_unique UNIQUE (parent_subject_id, name),
  CONSTRAINT subjects_parent_subject_id_fkey FOREIGN KEY (parent_subject_id, parent_subject_kind) REFERENCES subjects (id, kind),
  CONSTRAINT subjects_parent_must_be_group CHECK (
    (
      parent_subject_id IS NULL
      AND parent_subject_kind IS NULL
    ) OR (
      parent_subject_id IS NOT NULL
      AND parent_subject_kind = 'group'
    )
  ),
  CONSTRAINT subjects_not_self_parent CHECK (parent_subject_id IS NULL OR parent_subject_id <> id)
);

CREATE UNIQUE INDEX subjects_root_name_unique ON subjects (name) WHERE parent_subject_id IS NULL;

CREATE TEMP TABLE canonical_subjects AS
WITH subject_candidates AS (
  SELECT
    1 AS source_priority,
    COALESCE(NULLIF(btrim(regexp_replace(category, '[[:space:]]+', ' ', 'g')), ''), 'Untitled Subject') AS display_name,
    created_at,
    updated_at
  FROM subjects_legacy
  UNION ALL
  SELECT
    2 AS source_priority,
    COALESCE(NULLIF(btrim(regexp_replace(subject, '[[:space:]]+', ' ', 'g')), ''), 'Untitled Subject') AS display_name,
    created_at,
    created_at AS updated_at
  FROM student_grades
),
ranked_subjects AS (
  SELECT
    lower(display_name) AS canonical_key,
    display_name,
    created_at,
    updated_at,
    source_priority,
    row_number() OVER (
      PARTITION BY lower(display_name)
      ORDER BY source_priority ASC, length(display_name) ASC, display_name ASC
    ) AS canonical_name_rank,
    min(created_at) OVER (PARTITION BY lower(display_name)) AS first_created_at,
    max(updated_at) OVER (PARTITION BY lower(display_name)) AS last_updated_at
  FROM subject_candidates
),
subject_representatives AS (
  SELECT
    canonical_key,
    display_name,
    first_created_at,
    last_updated_at,
    COALESCE(
      NULLIF(btrim(regexp_replace(lower(display_name), '[^a-z0-9]+', '-', 'g'), '-'), ''),
      'subject'
    ) AS slug_base
  FROM ranked_subjects
  WHERE canonical_name_rank = 1
),
slugged_subjects AS (
  SELECT
    canonical_key,
    display_name,
    first_created_at,
    last_updated_at,
    slug_base,
    row_number() OVER (PARTITION BY slug_base ORDER BY canonical_key ASC) AS slug_rank
  FROM subject_representatives
)
SELECT
  canonical_key,
  display_name AS name,
  CASE
    WHEN slug_rank = 1 THEN slug_base
    ELSE slug_base || '-' || slug_rank
  END AS slug,
  first_created_at AS created_at,
  last_updated_at AS updated_at
FROM slugged_subjects;

CREATE TEMP TABLE inserted_subjects (
  id integer NOT NULL,
  slug text NOT NULL
);

WITH inserted_rows AS (
  INSERT INTO subjects (name, slug, kind, parent_subject_id, parent_subject_kind, is_active, created_at, updated_at)
SELECT
  name,
  slug,
  'leaf'::subject_kind,
  NULL,
  NULL,
  true,
  created_at,
  updated_at
FROM canonical_subjects
  RETURNING id, slug
)
INSERT INTO inserted_subjects (id, slug)
SELECT id, slug
FROM inserted_rows;

ALTER TABLE canonical_subjects
  ADD COLUMN subject_id integer;

UPDATE canonical_subjects
SET subject_id = inserted_subjects.id
FROM inserted_subjects
WHERE canonical_subjects.slug = inserted_subjects.slug;

CREATE TABLE tutor_subjects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id integer NOT NULL REFERENCES tutors (id),
  subject_id integer NOT NULL,
  subject_kind subject_kind NOT NULL DEFAULT 'leaf',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tutor_subjects_tutor_id_subject_id_unique UNIQUE (tutor_id, subject_id),
  CONSTRAINT tutor_subjects_subject_id_subject_kind_fkey FOREIGN KEY (subject_id, subject_kind) REFERENCES subjects (id, kind),
  CONSTRAINT tutor_subjects_leaf_only CHECK (subject_kind = 'leaf')
);

CREATE TEMP TABLE subject_id_map AS
SELECT
  subjects_legacy.id AS legacy_subject_id,
  subjects_legacy.tutor_id,
  canonical_subjects.subject_id
FROM subjects_legacy
JOIN canonical_subjects
  ON canonical_subjects.canonical_key = lower(
    COALESCE(NULLIF(btrim(regexp_replace(subjects_legacy.category, '[[:space:]]+', ' ', 'g')), ''), 'Untitled Subject')
  );

INSERT INTO tutor_subjects (tutor_id, subject_id, subject_kind, created_at, updated_at)
SELECT
  subject_id_map.tutor_id,
  subject_id_map.subject_id,
  'leaf'::subject_kind,
  min(subjects_legacy.created_at) AS created_at,
  max(subjects_legacy.updated_at) AS updated_at
FROM subject_id_map
JOIN subjects_legacy
  ON subjects_legacy.id = subject_id_map.legacy_subject_id
GROUP BY subject_id_map.tutor_id, subject_id_map.subject_id;

WITH inferred_student_parents AS (
  SELECT
    student_id,
    min(parent_id) AS parent_id
  FROM sessions
  GROUP BY student_id
  HAVING count(DISTINCT parent_id) = 1
)
UPDATE students
SET parent_id = inferred_student_parents.parent_id
FROM inferred_student_parents
WHERE students.id = inferred_student_parents.student_id
  AND students.parent_id IS NULL;

ALTER TABLE sessions
  DROP CONSTRAINT IF EXISTS sessions_subject_id_fkey,
  DROP CONSTRAINT IF EXISTS sessions_subject_id_subjects_id_fk,
  DROP CONSTRAINT IF EXISTS sessions_tutor_id_fkey,
  DROP CONSTRAINT IF EXISTS sessions_student_id_fkey,
  DROP CONSTRAINT IF EXISTS sessions_tutor_id_subject_id_fkey,
  DROP CONSTRAINT IF EXISTS sessions_student_id_parent_id_fkey,
  DROP CONSTRAINT IF EXISTS sessions_slot_units_positive,
  DROP CONSTRAINT IF EXISTS sessions_ends_after_start,
  DROP CONSTRAINT IF EXISTS sessions_slot_units_match_range;

UPDATE sessions
SET subject_id = subject_id_map.subject_id
FROM subject_id_map
WHERE sessions.subject_id = subject_id_map.legacy_subject_id;

UPDATE sessions
SET parent_id = students.parent_id
FROM students
WHERE sessions.student_id = students.id
  AND students.parent_id IS NOT NULL
  AND sessions.parent_id IS DISTINCT FROM students.parent_id;

ALTER TABLE students
  DROP CONSTRAINT IF EXISTS students_id_parent_id_unique,
  ADD CONSTRAINT students_id_parent_id_unique UNIQUE (id, parent_id);

ALTER TABLE sessions
  ALTER COLUMN slot_units SET DEFAULT 2,
  ADD CONSTRAINT sessions_student_id_parent_id_fkey FOREIGN KEY (student_id, parent_id) REFERENCES students (id, parent_id),
  ADD CONSTRAINT sessions_tutor_id_subject_id_fkey FOREIGN KEY (tutor_id, subject_id) REFERENCES tutor_subjects (tutor_id, subject_id),
  ADD CONSTRAINT sessions_slot_units_positive CHECK (slot_units > 0),
  ADD CONSTRAINT sessions_ends_after_start CHECK (ends_at > scheduled_at),
  ADD CONSTRAINT sessions_slot_units_match_range CHECK (
    ends_at = scheduled_at + (slot_units * interval '30 minutes')
  );

ALTER TABLE student_grades
  DROP CONSTRAINT IF EXISTS student_grades_subject_id_subject_kind_fkey,
  DROP CONSTRAINT IF EXISTS student_grades_leaf_only,
  ADD COLUMN subject_id integer,
  ADD COLUMN subject_kind subject_kind;

UPDATE student_grades
SET
  subject_id = canonical_subjects.subject_id,
  subject_kind = 'leaf'::subject_kind
FROM canonical_subjects
WHERE canonical_subjects.canonical_key = lower(
  COALESCE(NULLIF(btrim(regexp_replace(student_grades.subject, '[[:space:]]+', ' ', 'g')), ''), 'Untitled Subject')
);

ALTER TABLE student_grades
  ALTER COLUMN subject_id SET NOT NULL,
  ALTER COLUMN subject_kind SET NOT NULL,
  ALTER COLUMN subject_kind SET DEFAULT 'leaf',
  DROP COLUMN subject,
  ADD CONSTRAINT student_grades_subject_id_subject_kind_fkey FOREIGN KEY (subject_id, subject_kind) REFERENCES subjects (id, kind),
  ADD CONSTRAINT student_grades_leaf_only CHECK (subject_kind = 'leaf');

DELETE FROM session_progress
WHERE id IN (
  SELECT id
  FROM (
    SELECT
      id,
      row_number() OVER (PARTITION BY session_id ORDER BY updated_at DESC, created_at DESC, id DESC) AS progress_rank
    FROM session_progress
  ) ranked_session_progress
  WHERE progress_rank > 1
);

ALTER TABLE session_progress
  DROP CONSTRAINT IF EXISTS session_progress_session_id_unique,
  ADD CONSTRAINT session_progress_session_id_unique UNIQUE (session_id);

DELETE FROM session_metrics
WHERE session_id IS NULL;

DELETE FROM session_metrics
WHERE id IN (
  SELECT id
  FROM (
    SELECT
      id,
      row_number() OVER (PARTITION BY session_id ORDER BY updated_at DESC, recorded_at DESC, id DESC) AS metrics_rank
    FROM session_metrics
  ) ranked_session_metrics
  WHERE metrics_rank > 1
);

ALTER TABLE session_metrics
  DROP CONSTRAINT IF EXISTS session_metrics_student_id_fkey,
  DROP CONSTRAINT IF EXISTS session_metrics_session_id_unique,
  ALTER COLUMN session_id SET NOT NULL,
  DROP COLUMN student_id,
  ADD CONSTRAINT session_metrics_session_id_unique UNIQUE (session_id);

WITH ranked_credit_balances AS (
  SELECT
    id,
    row_number() OVER (PARTITION BY parent_id ORDER BY updated_at DESC, created_at DESC, id DESC) AS balance_rank,
    sum(amount_available) OVER (PARTITION BY parent_id) AS total_available,
    sum(amount_pending) OVER (PARTITION BY parent_id) AS total_pending,
    min(created_at) OVER (PARTITION BY parent_id) AS first_created_at,
    max(updated_at) OVER (PARTITION BY parent_id) AS last_updated_at
  FROM credit_balances
)
UPDATE credit_balances
SET
  amount_available = ranked_credit_balances.total_available,
  amount_pending = ranked_credit_balances.total_pending,
  created_at = ranked_credit_balances.first_created_at,
  updated_at = ranked_credit_balances.last_updated_at
FROM ranked_credit_balances
WHERE credit_balances.id = ranked_credit_balances.id
  AND ranked_credit_balances.balance_rank = 1;

DELETE FROM credit_balances
WHERE id IN (
  SELECT id
  FROM (
    SELECT
      id,
      row_number() OVER (PARTITION BY parent_id ORDER BY updated_at DESC, created_at DESC, id DESC) AS balance_rank
    FROM credit_balances
  ) ranked_credit_balances
  WHERE balance_rank > 1
);

ALTER TABLE credit_balances
  DROP CONSTRAINT IF EXISTS credit_balances_parent_id_unique,
  DROP CONSTRAINT IF EXISTS credit_balances_available_nonnegative,
  DROP CONSTRAINT IF EXISTS credit_balances_pending_nonnegative,
  ALTER COLUMN amount_available SET DEFAULT 0,
  ALTER COLUMN amount_pending SET DEFAULT 0,
  ADD CONSTRAINT credit_balances_parent_id_unique UNIQUE (parent_id),
  ADD CONSTRAINT credit_balances_available_nonnegative CHECK (amount_available >= 0),
  ADD CONSTRAINT credit_balances_pending_nonnegative CHECK (amount_pending >= 0);

ALTER TABLE credit_transactions
  DROP CONSTRAINT IF EXISTS credit_transactions_idempotency_key_unique,
  DROP CONSTRAINT IF EXISTS credit_transactions_nonzero_delta,
  DROP CONSTRAINT IF EXISTS credit_transactions_available_after_nonnegative,
  DROP CONSTRAINT IF EXISTS credit_transactions_pending_after_nonnegative,
  ADD COLUMN available_delta integer,
  ADD COLUMN pending_delta integer,
  ADD COLUMN available_after integer,
  ADD COLUMN pending_after integer,
  ADD COLUMN idempotency_key text,
  ADD COLUMN note text;

UPDATE credit_transactions
SET
  available_delta = amount,
  pending_delta = CASE
    WHEN type = 'reservation' THEN GREATEST(amount * -1, 0)
    ELSE 0
  END,
  available_after = balance_after,
  note = 'Legacy student_id=' || student_id;

WITH transaction_running_pending AS (
  SELECT
    id,
    sum(pending_delta) OVER (PARTITION BY parent_id ORDER BY created_at ASC, id ASC) AS running_pending_after
  FROM credit_transactions
)
UPDATE credit_transactions
SET pending_after = transaction_running_pending.running_pending_after
FROM transaction_running_pending
WHERE credit_transactions.id = transaction_running_pending.id;

ALTER TABLE credit_transactions
  ALTER COLUMN available_delta SET NOT NULL,
  ALTER COLUMN available_delta SET DEFAULT 0,
  ALTER COLUMN pending_delta SET NOT NULL,
  ALTER COLUMN pending_delta SET DEFAULT 0,
  ALTER COLUMN available_after SET NOT NULL,
  ALTER COLUMN pending_after SET NOT NULL,
  DROP COLUMN student_id,
  DROP COLUMN amount,
  DROP COLUMN balance_after,
  ADD CONSTRAINT credit_transactions_idempotency_key_unique UNIQUE (idempotency_key),
  ADD CONSTRAINT credit_transactions_nonzero_delta CHECK (available_delta <> 0 OR pending_delta <> 0),
  ADD CONSTRAINT credit_transactions_available_after_nonnegative CHECK (available_after >= 0),
  ADD CONSTRAINT credit_transactions_pending_after_nonnegative CHECK (pending_after >= 0);

DROP TABLE subjects_legacy;
